name: Check DJI SDK Release Note for Changes

on:
  schedule:
    # Runs every day at 00:00 UTC (adjust the cron expression for your preferred time)
    - cron: "0 0 * * *"

  workflow_dispatch: # allows manual trigger of the workflow

jobs:
  check_dji_page:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22.9'
      - run: npm ci

      # Fetch the current page content
      - name: Fetch DJI SDK Release Note
        run: node get-release-date.js

      # Compare the current page with the previous one
      - name: Compare with previous version
        id: diff_check
        run: |
          VERSION=$(cat current-version.txt)
          if [ $VERSION != ${{vars.SDK_VERSION}} ]; then
            echo "New version released"
            echo "new_version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "First run or no previous version found"
          fi

      # Send Slack notification if changes are detected
      - name: Send Slack notification if content changed
        if: steps.diff_check.outputs.new_version != ''
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "message": "${{steps.diff_check.outputs.new_version}} of DJI Mobile SDK has been released. Check it out at https://developer.dji.com/doc/mobile-sdk-tutorial/en/"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
